name: crud_objectbox
description: A CRUD demo with ObjectBox

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  objectbox: ^0.14.0            # to create and maintain the database,
  objectbox_flutter_libs: any   # to provide flutter-runtime libraries for the objectbox,
  path_provider: ^1.6.27        # to provide the path to the application's document directory to store the database,

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0          # to generate dart files for using our code, and
  objectbox_generator: any      # will generate the files using build_runner.

flutter:
  uses-material-design: true